# Generated by Django 4.2.4 on 2023-08-28 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleProtocol',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleStatus',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_ip_orig', models.CharField(blank=True, max_length=100, null=True)),
                ('source_ip_nat', models.CharField(blank=True, max_length=100, null=True)),
                ('source_port', models.PositiveIntegerField(null=True)),
                ('destination_name', models.CharField(max_length=100)),
                ('destination_ip_orig', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_ip_nat', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_port', models.PositiveIntegerField(null=True)),
                ('requester', models.CharField(max_length=70)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('ticket', models.CharField(blank=True, max_length=20, null=True)),
                ('firewalls', models.JSONField(null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action', models.ForeignKey(default='PER', on_delete=django.db.models.deletion.PROTECT, to='rules.ruleaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.ruleprotocol')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.rulestatus')),
            ],
        ),
    ]
