# Generated by Django 4.2.4 on 2023-08-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.CharField(choices=[('P', 'Permit'), ('D', 'Deny')], default='P', max_length=1),
        ),
    ]
