# Generated by Django 4.2.6 on 2023-12-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firewalls', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfirewallobject',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='historicalrule',
            name='action',
            field=models.CharField(choices=[('PER', 'Permit'), ('DEN', 'Deny')], max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalrule_firewalls',
            name='firewallobject',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='firewalls.firewallobject'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.CharField(choices=[('PER', 'Permit'), ('DEN', 'Deny')], max_length=3),
        ),
        migrations.AlterField(
            model_name='rule',
            name='firewalls',
            field=models.ManyToManyField(related_name='rule_firewalls', to='firewalls.firewallobject'),
        ),
        migrations.DeleteModel(
            name='FirewallObject',
        ),
        migrations.DeleteModel(
            name='HistoricalFirewallObject',
        ),
    ]
