# Generated by Django 4.2.4 on 2023-08-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallObject',
            fields=[
                ('hostname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='rule',
            name='firewalls',
        ),
        migrations.AddField(
            model_name='rule',
            name='firewalls',
            field=models.ManyToManyField(to='rules.firewallobject'),
        ),
    ]
