@startuml

left to right direction

skinparam actorStyle awesome
skinparam ranksep 150

actor "NW-Admin" as nwadmin #indianred
actor "Normal-User" as user #palegreen
actor "Auditor" as auditor #lightblue

package Auth {
  usecase "View Permission" as view_permission
  usecase "View Group" as view_group
  usecase "View User" as view_user
}

package Histories {
  usecase "View FirewallObject-History" as view_historicalfirewallobject
  usecase "View Rule-History" as view_historicalrule
  usecase "View Rule-Firewalls-History" as view_historicalrule_firewalls
  usecase "View RuleSetRequest-History" as view_historicalrulesetrequest
}

package FirewallObject {
  usecase "Add FirewallObject" as add_firewallobject
  usecase "Change FirewallObject" as change_firewallobject
  usecase "Delete FirewallObject" as delete_firewallobject
  usecase "View FirewallObject" as view_firewallobject
}

package Rule {
  usecase "Add Rule" as add_rule
  usecase "Change Rule" as change_rule
  usecase "Delete Rule" as delete_rule
  usecase "View Rule" as view_rule
}

package RuleSetRequest {
  usecase "Add RuleSetRequest" as add_rulesetrequest
  usecase "Change RuleSetRequest" as change_rulesetrequest
  usecase "Delete RuleSetRequest" as delete_rulesetrequest
  usecase "View RuleSetRequest" as view_rulesetrequest
}

nwadmin -u[#red,bold]-> view_permission
nwadmin -u[#red,bold]-> view_group
nwadmin -u[#red,bold]-> view_user
nwadmin -u[#red,bold]-> view_historicalfirewallobject
nwadmin -u[#red,bold]-> view_historicalrule
nwadmin -u[#red,bold]-> view_historicalrule_firewalls
nwadmin -u[#red,bold]-> view_historicalrulesetrequest
nwadmin -u[#red,bold]-> add_firewallobject
nwadmin -u[#red,bold]-> change_firewallobject
nwadmin -u[#red,bold]-> delete_firewallobject
nwadmin -u[#red,bold]-> view_firewallobject
nwadmin -u[#red,bold]-> add_rule
nwadmin -u[#red,bold]-> change_rule
nwadmin -u[#red,bold]-> delete_rule
nwadmin -u[#red,bold]-> view_rule
nwadmin -u[#red,bold]-> add_rulesetrequest
nwadmin -u[#red,bold]-> change_rulesetrequest
nwadmin -u[#red,bold]-> delete_rulesetrequest
nwadmin -u[#red,bold]-> view_rulesetrequest

auditor -[#blue,bold]-> view_user
auditor -[#blue,bold]-> view_firewallobject
auditor -[#blue,bold]-> view_historicalrule
auditor -[#blue,bold]-> view_historicalrule_firewalls
auditor -[#blue,bold]-> view_rule
auditor -[#blue,bold]-> view_historicalrulesetrequest
auditor -[#blue,bold]-> view_rulesetrequest

user -[#green,bold]-> view_user
user -[#green,bold]-> view_firewallobject
user -[#green,bold]-> view_historicalrule
user -[#green,bold]-> view_historicalrule_firewalls
user -[#green,bold]-> add_rule
user -[#green,bold]-> view_rule
user -[#green,bold]-> view_historicalrulesetrequest
user -[#green,bold]-> add_rulesetrequest
user -[#green,bold]-> view_rulesetrequest
@enduml